### ISSUE TITLE
PLEASE UPDATE

### ISSUE THREAD

**Issue by Adhaaz** [an678-mhg/Movie-TS#1]
Please add PlayerKey in video player.

If you can, add it too
- TMDB api as an alternative url base other than loklok (To make a more complete collection of films and series on website 😃)
- Also use Api Embed https://2embed.org as another alternative video player

Thank you, Hope this request of mine is as soon as possible added to this script code

**Comment by an678-mhg** [comment]
Thank you i will fix it right away
