### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by jexii-new** [an678-mhg/Movie-TS#2]
![Screenshot_2022-08-13-06-01-43-22_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/86584901/184455323-d5e1428c-1152-4ebf-8a9a-85362d97b2a9.jpg)

Excuse me sir, I like your project, can I ask u? Please add a download button in the Video player like in this picture. Thank u sir ❤️

**Comment by an678-mhg** [comment]
I'm sorry but because the video is in m3u8 format, I can't download it

**Comment by jexii-new** [comment]
Oh, like that, I guess u could add a download button like the one in that picture
